site_name: OrbitalPlay Docs
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Interactive Notebooks: notebooks.md
  - User Guide: user-guide.md
  - Theory: theory.md
  - Developer Guide: developer.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  google_site_verification: google7f0d84bcdb02d19b
